// Nifty 500 Universe — auto-generated from NSE index constituents
// Updated: 2026-03-24

export const NSE_UNIVERSE: { symbol: string; name: string }[] = [
  { symbol: "360ONE.NS", name: "360 ONE WAM" },
  { symbol: "3MINDIA.NS", name: "3M INDIA" },
  { symbol: "ABB.NS", name: "ABB INDIA" },
  { symbol: "ACC.NS", name: "ACC" },
  { symbol: "ACMESOLAR.NS", name: "ACME SOLAR HOLDINGS" },
  { symbol: "AIAENG.NS", name: "AIA ENGINEERING" },
  { symbol: "APLAPOLLO.NS", name: "APL APOLLO TUBES" },
  { symbol: "AUBANK.NS", name: "AU SMALL FINANCE BANK" },
  { symbol: "AWL.NS", name: "AWL AGRI BUSINESS" },
  { symbol: "AADHARHFC.NS", name: "AADHAR HOUSING FINANCE L" },
  { symbol: "AARTIIND.NS", name: "AARTI INDUSTRIES" },
  { symbol: "AAVAS.NS", name: "AAVAS FINANCIERS" },
  { symbol: "ABBOTINDIA.NS", name: "ABBOTT INDIA" },
  { symbol: "ACE.NS", name: "ACTION CONST EQUIP" },
  { symbol: "ADANIENSOL.NS", name: "ADANI ENERGY SOLUTION" },
  { symbol: "ADANIENT.NS", name: "ADANI ENTERPRISES" },
  { symbol: "ADANIGREEN.NS", name: "ADANI GREEN ENERGY" },
  { symbol: "ADANIPORTS.NS", name: "ADANI PORT & SEZ" },
  { symbol: "ADANIPOWER.NS", name: "ADANI POWER" },
  { symbol: "ATGL.NS", name: "ADANI TOTAL GAS" },
  { symbol: "ABCAPITAL.NS", name: "ADITYA BIRLA CAPITAL" },
  { symbol: "ABFRL.NS", name: "ADITYA BIRLA FASHION & RT" },
  { symbol: "ABLBL.NS", name: "ADITYA BIRLA LIFES BRAN L" },
  { symbol: "ABREL.NS", name: "ADITYA BIRLA REAL EST" },
  { symbol: "ABSLAMC.NS", name: "ADIT BIRL SUN LIF AMC" },
  { symbol: "AEGISLOG.NS", name: "AEGIS LOGISTICS" },
  { symbol: "AEGISVOPAK.NS", name: "AEGIS VOPAK TERMINALS" },
  { symbol: "AFCONS.NS", name: "AFCONS INFRASTRUCTURE" },
  { symbol: "AFFLE.NS", name: "AFFLE 3I" },
  { symbol: "AJANTPHARM.NS", name: "AJANTA PHARMA" },
  { symbol: "AKUMS.NS", name: "AKUMS DRUGS AND PHARMA L" },
  { symbol: "AKZOINDIA.NS", name: "AKZO NOBEL INDIA" },
  { symbol: "APLLTD.NS", name: "ALEMBIC PHARMA" },
  { symbol: "ALKEM.NS", name: "ALKEM LABORATORIES" },
  { symbol: "ALKYLAMINE.NS", name: "ALKYL AMINES CHEM." },
  { symbol: "ALOKINDS.NS", name: "ALOK INDUSTRIES" },
  { symbol: "ARE&M.NS", name: "AMARA RAJA ENERGY MOB" },
  { symbol: "AMBER.NS", name: "AMBER ENTERPRISES (I)" },
  { symbol: "AMBUJACEM.NS", name: "AMBUJA CEMENTS" },
  { symbol: "ANANDRATHI.NS", name: "ANAND RATHI WEALTH" },
  { symbol: "ANANTRAJ.NS", name: "ANANT RAJ" },
  { symbol: "ANGELONE.NS", name: "ANGEL ONE" },
  { symbol: "APARINDS.NS", name: "APAR INDUSTRIES" },
  { symbol: "APOLLOHOSP.NS", name: "APOLLO HOSPITALS ENTER. L" },
  { symbol: "APOLLOTYRE.NS", name: "APOLLO TYRES" },
  { symbol: "APTUS.NS", name: "APTUS VALUE HSG FIN I" },
  { symbol: "ASAHIINDIA.NS", name: "ASAHI INDIA GLASS" },
  { symbol: "ASHOKLEY.NS", name: "ASHOK LEYLAND" },
  { symbol: "ASIANPAINT.NS", name: "ASIAN PAINTS" },
  { symbol: "ASTERDM.NS", name: "ASTER DM HEALTHCARE" },
  { symbol: "ASTRAZEN.NS", name: "ASTRAZENECA PHARMA IND LT" },
  { symbol: "ASTRAL.NS", name: "ASTRAL" },
  { symbol: "ATHERENERG.NS", name: "ATHER ENERGY" },
  { symbol: "ATUL.NS", name: "ATUL" },
  { symbol: "AUROPHARMA.NS", name: "AUROBINDO PHARMA" },
  { symbol: "AIIL.NS", name: "AUTHUM INVEST & INFRA" },
  { symbol: "DMART.NS", name: "AVENUE SUPERMARTS" },
  { symbol: "AXISBANK.NS", name: "AXIS BANK" },
  { symbol: "BASF.NS", name: "BASF INDIA" },
  { symbol: "BEML.NS", name: "BEML" },
  { symbol: "BLS.NS", name: "BLS INTL SERVS" },
  { symbol: "BSE.NS", name: "BSE" },
  { symbol: "BAJAJ-AUTO.NS", name: "BAJAJ AUTO" },
  { symbol: "BAJFINANCE.NS", name: "BAJAJ FINANCE" },
  { symbol: "BAJAJFINSV.NS", name: "BAJAJ FINSERV" },
  { symbol: "BAJAJHLDNG.NS", name: "BAJAJ HOLDINGS & INVS" },
  { symbol: "BAJAJHFL.NS", name: "BAJAJ HOUSING FINANCE" },
  { symbol: "BALKRISIND.NS", name: "BALKRISHNA IND." },
  { symbol: "BALRAMCHIN.NS", name: "BALRAMPUR CHINI MILLS" },
  { symbol: "BANDHANBNK.NS", name: "BANDHAN BANK" },
  { symbol: "BANKBARODA.NS", name: "BANK OF BARODA" },
  { symbol: "BANKINDIA.NS", name: "BANK OF INDIA" },
  { symbol: "MAHABANK.NS", name: "BANK OF MAHARASHTRA" },
  { symbol: "BATAINDIA.NS", name: "BATA INDIA" },
  { symbol: "BAYERCROP.NS", name: "BAYER CROPSCIENCE" },
  { symbol: "BERGEPAINT.NS", name: "BERGER PAINTS (I)" },
  { symbol: "BDL.NS", name: "BHARAT DYNAMICS" },
  { symbol: "BEL.NS", name: "BHARAT ELECTRONICS" },
  { symbol: "BHARATFORG.NS", name: "BHARAT FORGE" },
  { symbol: "BHEL.NS", name: "BHEL" },
  { symbol: "BPCL.NS", name: "BHARAT PETROLEUM CORP  LT" },
  { symbol: "BHARTIARTL.NS", name: "BHARTI AIRTEL" },
  { symbol: "BHARTIHEXA.NS", name: "BHARTI HEXACOM" },
  { symbol: "BIKAJI.NS", name: "BIKAJI FOODS INTERN" },
  { symbol: "BIOCON.NS", name: "BIOCON" },
  { symbol: "BSOFT.NS", name: "BIRLASOFT" },
  { symbol: "BLUEDART.NS", name: "BLUE DART EXPRESS" },
  { symbol: "BLUEJET.NS", name: "BLUE JET HEALTHCARE" },
  { symbol: "BLUESTARCO.NS", name: "BLUE STAR" },
  { symbol: "BBTC.NS", name: "BOMBAY BURMAH TRADING COR" },
  { symbol: "BOSCHLTD.NS", name: "BOSCH" },
  { symbol: "FIRSTCRY.NS", name: "BRAINBEES SOLUTIONS" },
  { symbol: "BRIGADE.NS", name: "BRIGADE ENTER." },
  { symbol: "BRITANNIA.NS", name: "BRITANNIA INDUSTRIES" },
  { symbol: "MAPMYINDIA.NS", name: "C.E. INFO SYSTEMS" },
  { symbol: "CCL.NS", name: "CCL PRODUCTS (I)" },
  { symbol: "CESC.NS", name: "CESC" },
  { symbol: "CGPOWER.NS", name: "CG POWER AND IND SOL" },
  { symbol: "CRISIL.NS", name: "CRISIL" },
  { symbol: "CAMPUS.NS", name: "CAMPUS ACTIVEWEAR" },
  { symbol: "CANFINHOME.NS", name: "CAN FIN HOMES" },
  { symbol: "CANBK.NS", name: "CANARA BANK" },
  { symbol: "CAPLIPOINT.NS", name: "CAPLIN POINT LAB" },
  { symbol: "CGCL.NS", name: "CAPRI GLOBAL CAPITAL" },
  { symbol: "CARBORUNIV.NS", name: "CARBORUNDUM UNIVERSAL" },
  { symbol: "CASTROLIND.NS", name: "CASTROL INDIA" },
  { symbol: "CEATLTD.NS", name: "CEAT" },
  { symbol: "CENTRALBK.NS", name: "CENTRAL BANK OF INDIA" },
  { symbol: "CDSL.NS", name: "CENTRAL DEPO SER (I)" },
  { symbol: "CENTURYPLY.NS", name: "CENTURY PLYBOARDS (I)" },
  { symbol: "CERA.NS", name: "CERA SANITARYWARE" },
  { symbol: "CHALET.NS", name: "CHALET HOTELS" },
  { symbol: "CHAMBLFERT.NS", name: "CHAMBAL FERTILIZERS" },
  { symbol: "CHENNPETRO.NS", name: "CHENNAI PETROLEUM CORP LT" },
  { symbol: "CHOICEIN.NS", name: "CHOICE INTERNATIONAL" },
  { symbol: "CHOLAHLDNG.NS", name: "CHOLAMANDALAM FIN HOL" },
  { symbol: "CHOLAFIN.NS", name: "CHOLAMANDALAM IN & FIN CO" },
  { symbol: "CIPLA.NS", name: "CIPLA" },
  { symbol: "CUB.NS", name: "CITY UNION BANK" },
  { symbol: "CLEAN.NS", name: "CLEAN SCIENCE & TECH" },
  { symbol: "COALINDIA.NS", name: "COAL INDIA" },
  { symbol: "COCHINSHIP.NS", name: "COCHIN SHIPYARD" },
  { symbol: "COFORGE.NS", name: "COFORGE" },
  { symbol: "COHANCE.NS", name: "COHANCE LIFESCIENCES" },
  { symbol: "COLPAL.NS", name: "COLGATE PALMOLIVE" },
  { symbol: "CAMS.NS", name: "COMPUTER AGE MNGT SER" },
  { symbol: "CONCORDBIO.NS", name: "CONCORD BIOTECH" },
  { symbol: "CONCOR.NS", name: "CONTAINER CORP OF IND" },
  { symbol: "COROMANDEL.NS", name: "COROMANDEL INTERNTL." },
  { symbol: "CRAFTSMAN.NS", name: "CRAFTSMAN AUTOMATION" },
  { symbol: "CREDITACC.NS", name: "CREDITACCESS GRAMEEN" },
  { symbol: "CROMPTON.NS", name: "CROMPT GREA CON ELEC" },
  { symbol: "CUMMINSIND.NS", name: "CUMMINS INDIA" },
  { symbol: "CYIENT.NS", name: "CYIENT" },
  { symbol: "DCMSHRIRAM.NS", name: "DCM SHRIRAM" },
  { symbol: "DLF.NS", name: "DLF" },
  { symbol: "DOMS.NS", name: "DOMS INDUSTRIES" },
  { symbol: "DABUR.NS", name: "DABUR INDIA" },
  { symbol: "DALBHARAT.NS", name: "DALMIA BHARAT" },
  { symbol: "DATAPATTNS.NS", name: "DATA PATTERNS INDIA" },
  { symbol: "DEEPAKFERT.NS", name: "DEEPAK FERTILIZERS & PETR" },
  { symbol: "DEEPAKNTR.NS", name: "DEEPAK NITRITE" },
  { symbol: "DELHIVERY.NS", name: "DELHIVERY" },
  { symbol: "DEVYANI.NS", name: "DEVYANI INTERNATIONAL" },
  { symbol: "DIVISLAB.NS", name: "DIVI S LABORATORIES" },
  { symbol: "DIXON.NS", name: "DIXON TECHNO (INDIA)" },
  { symbol: "AGARWALEYE.NS", name: "DR AGARWALS HEALTH CARE L" },
  { symbol: "LALPATHLAB.NS", name: "DR. LAL PATH LABS" },
  { symbol: "DRREDDY.NS", name: "DR. REDDY S LABORATORIES" },
  { symbol: "EIDPARRY.NS", name: "EID PARRY INDIA" },
  { symbol: "EIHOTEL.NS", name: "EIH - OBEROI HOTELS" },
  { symbol: "EICHERMOT.NS", name: "EICHER MOTORS" },
  { symbol: "ELECON.NS", name: "ELECON ENG. CO." },
  { symbol: "ELGIEQUIP.NS", name: "ELGI EQUIPMENTS" },
  { symbol: "EMAMILTD.NS", name: "EMAMI" },
  { symbol: "EMCURE.NS", name: "EMCURE PHARMACEUTICALS L" },
  { symbol: "ENDURANCE.NS", name: "ENDURANCE TECHNO." },
  { symbol: "ENGINERSIN.NS", name: "ENGINEERS INDIA" },
  { symbol: "ERIS.NS", name: "ERIS LIFESCIENCES" },
  { symbol: "ESCORTS.NS", name: "ESCORTS KUBOTA" },
  { symbol: "ETERNAL.NS", name: "ETERNAL - ZOMATO" },
  { symbol: "EXIDEIND.NS", name: "EXIDE INDUSTRIES" },
  { symbol: "NYKAA.NS", name: "FSN E COMMERCE VENTURES" },
  { symbol: "FEDERALBNK.NS", name: "FEDERAL BANK" },
  { symbol: "FACT.NS", name: "FACT" },
  { symbol: "FINCABLES.NS", name: "FINOLEX CABLES" },
  { symbol: "FINPIPE.NS", name: "FINOLEX INDUSTRIES" },
  { symbol: "FSL.NS", name: "FIRSTSOURCE SOLU." },
  { symbol: "FIVESTAR.NS", name: "FIVE-STAR BUS FIN" },
  { symbol: "FORCEMOT.NS", name: "FORCE MOTORS" },
  { symbol: "FORTIS.NS", name: "FORTIS HEALTHCARE" },
  { symbol: "GAIL.NS", name: "GAIL (INDIA)" },
  { symbol: "GVT&D.NS", name: "GE VERNOVA T&D INDIA" },
  { symbol: "GMRAIRPORT.NS", name: "GMR AIRPORTS" },
  { symbol: "GRSE.NS", name: "GARDEN REACH SHIP&ENG" },
  { symbol: "GICRE.NS", name: "GENERAL INS CORP OF INDIA" },
  { symbol: "GILLETTE.NS", name: "GILLETTE INDIA" },
  { symbol: "GLAND.NS", name: "GLAND PHARMA" },
  { symbol: "GLAXO.NS", name: "GLAXOSMITHKLINE PHARMA LT" },
  { symbol: "GLENMARK.NS", name: "GLENMARK PHARMACEUTICALS" },
  { symbol: "MEDANTA.NS", name: "GLOBAL HEALTH" },
  { symbol: "GODIGIT.NS", name: "GO DIGIT GENERAL INS" },
  { symbol: "GPIL.NS", name: "GODAWARI POW & ISP" },
  { symbol: "GODFRYPHLP.NS", name: "GODFREY PHILLIPS INDIA LT" },
  { symbol: "GODREJAGRO.NS", name: "GODREJ AGROVET" },
  { symbol: "GODREJCP.NS", name: "GODREJ CONSUMER PRODUCTS" },
  { symbol: "GODREJIND.NS", name: "GODREJ INDUSTRIES" },
  { symbol: "GODREJPROP.NS", name: "GODREJ PROPERTIES" },
  { symbol: "GRANULES.NS", name: "GRANULES INDIA" },
  { symbol: "GRAPHITE.NS", name: "GRAPHITE INDIA" },
  { symbol: "GRASIM.NS", name: "GRASIM INDUSTRIES" },
  { symbol: "GRAVITA.NS", name: "GRAVITA INDIA" },
  { symbol: "GESHIP.NS", name: "THE GE SHPG.LTD" },
  { symbol: "FLUOROCHEM.NS", name: "GUJARAT FLUOROCHEM" },
  { symbol: "GUJGASLTD.NS", name: "GUJARAT GAS" },
  { symbol: "GMDCLTD.NS", name: "GUJARAT MINERAL DEV CORP" },
  { symbol: "GSPL.NS", name: "GUJARAT STATE PETRO" },
  { symbol: "HEG.NS", name: "HEG" },
  { symbol: "HBLENGINE.NS", name: "HBL ENGINEERING" },
  { symbol: "HCLTECH.NS", name: "HCL TECHNOLOGIES" },
  { symbol: "HDFCAMC.NS", name: "HDFC AMC" },
  { symbol: "HDFCBANK.NS", name: "HDFC BANK" },
  { symbol: "HDFCLIFE.NS", name: "HDFC LIFE INS CO" },
  { symbol: "HFCL.NS", name: "HFCL" },
  { symbol: "HAPPSTMNDS.NS", name: "HAPPIEST MINDS TECHNO" },
  { symbol: "HAVELLS.NS", name: "HAVELLS INDIA" },
  { symbol: "HEROMOTOCO.NS", name: "HERO MOTOCORP" },
  { symbol: "HEXT.NS", name: "HEXAWARE TECHNOLOGIES" },
  { symbol: "HSCL.NS", name: "HIMADRI SPECIALITY CHEM L" },
  { symbol: "HINDALCO.NS", name: "HINDALCO  INDUSTRIES " },
  { symbol: "HAL.NS", name: "HINDUSTAN AERONAUTICS" },
  { symbol: "HINDCOPPER.NS", name: "HINDUSTAN COPPER" },
  { symbol: "HINDPETRO.NS", name: "HINDUSTAN PETROLEUM CORP" },
  { symbol: "HINDUNILVR.NS", name: "HINDUSTAN UNILEVER" },
  { symbol: "HINDZINC.NS", name: "HINDUSTAN ZINC" },
  { symbol: "POWERINDIA.NS", name: "HITACHI ENERGY INDIA" },
  { symbol: "HOMEFIRST.NS", name: "HOME FIRST FIN CO IND" },
  { symbol: "HONASA.NS", name: "HONASA CONSUMER - MAMAEARTH" },
  { symbol: "HONAUT.NS", name: "HONEYWELL AUTOMATION IND" },
  { symbol: "HUDCO.NS", name: "HSG & URBAN DEV CORPN" },
  { symbol: "HYUNDAI.NS", name: "HYUNDAI MOTOR INDIA" },
  { symbol: "ICICIBANK.NS", name: "ICICI BANK" },
  { symbol: "ICICIGI.NS", name: "ICICI LOMBARD GIC" },
  { symbol: "ICICIPRULI.NS", name: "ICICI PRU LIFE INS CO" },
  { symbol: "IDBI.NS", name: "IDBI BANK" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC FIRST BANK" },
  { symbol: "IFCI.NS", name: "IFCI" },
  { symbol: "IIFL.NS", name: "IIFL FINANCE" },
  { symbol: "INOXINDIA.NS", name: "INOX INDIA" },
  { symbol: "IRB.NS", name: "IRB INFRA DEV" },
  { symbol: "IRCON.NS", name: "IRCON INTERNATIONAL" },
  { symbol: "ITCHOTELS.NS", name: "ITC HOTELS" },
  { symbol: "ITC.NS", name: "ITC" },
  { symbol: "ITI.NS", name: "ITI" },
  { symbol: "INDGN.NS", name: "INDEGENE" },
  { symbol: "INDIACEM.NS", name: "THE INDIA CEMENTS" },
  { symbol: "INDIAMART.NS", name: "INDIAMART INTERMESH" },
  { symbol: "INDIANB.NS", name: "INDIAN BANK" },
  { symbol: "IEX.NS", name: "INDIAN ENERGY EXC" },
  { symbol: "INDHOTEL.NS", name: "THE INDIAN HOTELS CO." },
  { symbol: "IOC.NS", name: "INDIAN OIL CORP" },
  { symbol: "IOB.NS", name: "INDIAN OVERSEAS BANK" },
  { symbol: "IRCTC.NS", name: "INDIAN RAIL TOUR CORP" },
  { symbol: "IRFC.NS", name: "INDIAN RAILWAY FIN CORP L" },
  { symbol: "IREDA.NS", name: "INDIAN RENEWABLE ENERGY" },
  { symbol: "IGL.NS", name: "INDRAPRASTHA GAS" },
  { symbol: "INDUSTOWER.NS", name: "INDUS TOWERS" },
  { symbol: "INDUSINDBK.NS", name: "INDUSIND BANK" },
  { symbol: "NAUKRI.NS", name: "INFO EDGE (I)" },
  { symbol: "INFY.NS", name: "INFOSYS" },
  { symbol: "INOXWIND.NS", name: "INOX WIND" },
  { symbol: "INTELLECT.NS", name: "INTELLECT DESIGN ARENA" },
  { symbol: "INDIGO.NS", name: "INTERGLOBE AVIATION" },
  { symbol: "IGIL.NS", name: "INTERNATIO GEMM INS (I) L" },
  { symbol: "IKS.NS", name: "INVENTURUS KNOWLEDGE SO L" },
  { symbol: "IPCALAB.NS", name: "IPCA LABORATORIES" },
  { symbol: "JBCHEPHARM.NS", name: "J B CHEMICALS AND PHARMA" },
  { symbol: "JKCEMENT.NS", name: "JK CEMENT" },
  { symbol: "JBMA.NS", name: "JBM AUTO" },
  { symbol: "JKTYRE.NS", name: "JK TYRE & INDUSTRIES" },
  { symbol: "JMFINANCIL.NS", name: "JM FINANCIAL" },
  { symbol: "JSWCEMENT.NS", name: "JSW CEMENT" },
  { symbol: "JSWENERGY.NS", name: "JSW ENERGY" },
  { symbol: "JSWINFRA.NS", name: "JSW INFRASTRUCTURE" },
  { symbol: "JSWSTEEL.NS", name: "JSW STEEL" },
  { symbol: "JPPOWER.NS", name: "JAIPRAKASH POWER VEN." },
  { symbol: "J&KBANK.NS", name: "J & K BANK" },
  { symbol: "JINDALSAW.NS", name: "JINDAL SAW" },
  { symbol: "JSL.NS", name: "JINDAL STAINLESS" },
  { symbol: "JINDALSTEL.NS", name: "JINDAL STEEL" },
  { symbol: "JIOFIN.NS", name: "JIO FIN SERVICES" },
  { symbol: "JUBLFOOD.NS", name: "JUBILANT FOODWORKS" },
  { symbol: "JUBLINGREA.NS", name: "JUBILANT INGREVIA" },
  { symbol: "JUBLPHARMA.NS", name: "JUBILANT PHARMOVA" },
  { symbol: "JWL.NS", name: "JUPITER WAGONS" },
  { symbol: "JYOTHYLAB.NS", name: "JYOTHY LABS" },
  { symbol: "JYOTICNC.NS", name: "JYOTI CNC AUTOMATION" },
  { symbol: "KPRMILL.NS", name: "KPR MILL" },
  { symbol: "KEI.NS", name: "KEI INDUSTRIES" },
  { symbol: "KPITTECH.NS", name: "KPIT TECHNOLOGIES" },
  { symbol: "KSB.NS", name: "KSB" },
  { symbol: "KAJARIACER.NS", name: "KAJARIA CERAMICS" },
  { symbol: "KPIL.NS", name: "KALPATARU PROJECT INT" },
  { symbol: "KALYANKJIL.NS", name: "KALYAN JEWELLERS IND" },
  { symbol: "KARURVYSYA.NS", name: "KARUR VYSYA BANK" },
  { symbol: "KAYNES.NS", name: "KAYNES TECHNOLOGY IND" },
  { symbol: "KEC.NS", name: "KEC INTL." },
  { symbol: "KFINTECH.NS", name: "KFIN TECHNOLOGIES" },
  { symbol: "KIRLOSBROS.NS", name: "KIRLOSKAR BROTHERS" },
  { symbol: "KIRLOSENG.NS", name: "KIRLOSKAR OIL ENG" },
  { symbol: "KOTAKBANK.NS", name: "KOTAK MAHINDRA BANK" },
  { symbol: "KIMS.NS", name: "KRISHNA INST OF MED SCI L" },
  { symbol: "LTF.NS", name: "L&T FINANCE" },
  { symbol: "LTTS.NS", name: "L&T TECHNOLOGY SER." },
  { symbol: "LICHSGFIN.NS", name: "LIC HOUSING FINANCE" },
  { symbol: "LTFOODS.NS", name: "LT FOODS" },
  { symbol: "LT.NS", name: "LARSEN & TOUBRO" },
  { symbol: "LATENTVIEW.NS", name: "LATENT VIEW ANALYTICS" },
  { symbol: "LAURUSLABS.NS", name: "LAURUS LABS" },
  { symbol: "THELEELA.NS", name: "LEELA PALACES HOTEL" },
  { symbol: "LEMONTREE.NS", name: "LEMON TREE HOTELS" },
  { symbol: "LICI.NS", name: "LIFE INSURA CORP OF INDIA" },
  { symbol: "LINDEINDIA.NS", name: "LINDE INDIA" },
  { symbol: "LLOYDSME.NS", name: "LLOYDS METALS N ENERGY L" },
  { symbol: "LODHA.NS", name: "LODHA DEVELOPERS" },
  { symbol: "LUPIN.NS", name: "LUPIN" },
  { symbol: "MMTC.NS", name: "MMTC" },
  { symbol: "MRF.NS", name: "MRF" },
  { symbol: "MGL.NS", name: "MAHANAGAR GAS" },
  { symbol: "MAHSCOOTER.NS", name: "MAHARASHTRA SCOOTERS" },
  { symbol: "MAHSEAMLES.NS", name: "MAHARASHTRA SEAMLESS" },
  { symbol: "M&MFIN.NS", name: "M&M FIN. SERVICES" },
  { symbol: "M&M.NS", name: "MAHINDRA & MAHINDRA" },
  { symbol: "MANAPPURAM.NS", name: "MANAPPURAM FINANCE" },
  { symbol: "MRPL.NS", name: "MRPL" },
  { symbol: "MANKIND.NS", name: "MANKIND PHARMA" },
  { symbol: "MARICO.NS", name: "MARICO" },
  { symbol: "MARUTI.NS", name: "MARUTI SUZUKI INDIA" },
  { symbol: "MFSL.NS", name: "MAX FINANCIAL SERV" },
  { symbol: "MAXHEALTH.NS", name: "MAX HEALTHCARE INS" },
  { symbol: "MAZDOCK.NS", name: "MAZAGON DOCK SHIPBUIL" },
  { symbol: "METROPOLIS.NS", name: "METROPOLIS HEALTHCARE" },
  { symbol: "MINDACORP.NS", name: "MINDA CORPORATION" },
  { symbol: "MSUMI.NS", name: "MOTHERSON SUMI WRNG IND L" },
  { symbol: "MOTILALOFS.NS", name: "MOTILAL OSWAL FIN" },
  { symbol: "MPHASIS.NS", name: "MPHASIS" },
  { symbol: "MCX.NS", name: "MULTI COMMODITY EXCHANGE" },
  { symbol: "MUTHOOTFIN.NS", name: "MUTHOOT FINANCE" },
  { symbol: "NATCOPHARM.NS", name: "NATCO PHARMA" },
  { symbol: "NBCC.NS", name: "NBCC (INDIA)" },
  { symbol: "NCC.NS", name: "NCC" },
  { symbol: "NHPC.NS", name: "NHPC" },
  { symbol: "NLCINDIA.NS", name: "NLC INDIA" },
  { symbol: "NMDC.NS", name: "NMDC" },
  { symbol: "NSLNISP.NS", name: "NMDC STEEL" },
  { symbol: "NTPCGREEN.NS", name: "NTPC GREEN ENERGY" },
  { symbol: "NTPC.NS", name: "NTPC" },
  { symbol: "NH.NS", name: "NARAYANA HRUDAYALAYA" },
  { symbol: "NATIONALUM.NS", name: "NATIONAL ALUMINIUM CO" },
  { symbol: "NAVA.NS", name: "NAVA" },
  { symbol: "NAVINFLUOR.NS", name: "NAVIN FLUORINE INT." },
  { symbol: "NESTLEIND.NS", name: "NESTLE INDIA" },
  { symbol: "NETWEB.NS", name: "NETWEB TECH INDIA" },
  { symbol: "NEULANDLAB.NS", name: "NEULAND LAB" },
  { symbol: "NEWGEN.NS", name: "NEWGEN SOFTWARE TECH" },
  { symbol: "NAM-INDIA.NS", name: "NIPPON L I A M" },
  { symbol: "NIVABUPA.NS", name: "NIVA BUPA HEALTH INS CO L" },
  { symbol: "NUVAMA.NS", name: "NUVAMA WEALTH MANAGE" },
  { symbol: "NUVOCO.NS", name: "NUVOCO VISTAS CORP" },
  { symbol: "OBEROIRLTY.NS", name: "OBEROI REALTY" },
  { symbol: "ONGC.NS", name: "OIL AND NATURAL GAS CORP." },
  { symbol: "OIL.NS", name: "OIL INDIA" },
  { symbol: "OLAELEC.NS", name: "OLA ELECTRIC MOBILITY" },
  { symbol: "OLECTRA.NS", name: "OLECTRA GREENTECH" },
  { symbol: "PAYTM.NS", name: "ONE 97 COMMUNICATIONS" },
  { symbol: "ONESOURCE.NS", name: "ONESOURCE SPECL PHARMA L" },
  { symbol: "OFSS.NS", name: "ORACLE FIN SERV SOFT" },
  { symbol: "POLICYBZR.NS", name: "PB FINTECH" },
  { symbol: "PCBL.NS", name: "PCBL CHEMICAL" },
  { symbol: "PGEL.NS", name: "PG ELECTROPLAST" },
  { symbol: "PIIND.NS", name: "PI INDUSTRIES" },
  { symbol: "PNBHOUSING.NS", name: "PNB HOUSING FIN" },
  { symbol: "PTCIL.NS", name: "PTC INDUSTRIES" },
  { symbol: "PVRINOX.NS", name: "PVR INOX" },
  { symbol: "PAGEIND.NS", name: "PAGE INDUSTRIES" },
  { symbol: "PATANJALI.NS", name: "PATANJALI FOODS" },
  { symbol: "PERSISTENT.NS", name: "PERSISTENT SYSTEMS" },
  { symbol: "PETRONET.NS", name: "PETRONET LNG" },
  { symbol: "PFIZER.NS", name: "PFIZER" },
  { symbol: "PHOENIXLTD.NS", name: "THE PHOENIX MILLS" },
  { symbol: "PIDILITIND.NS", name: "PIDILITE INDUSTRIES" },
  { symbol: "PPLPHARMA.NS", name: "PIRAMAL PHARMA" },
  { symbol: "POLYMED.NS", name: "POLY MEDICURE" },
  { symbol: "POLYCAB.NS", name: "POLYCAB INDIA" },
  { symbol: "POONAWALLA.NS", name: "POONAWALLA FINCORP" },
  { symbol: "PFC.NS", name: "POWER FIN CORP" },
  { symbol: "POWERGRID.NS", name: "POWER GRID CORP." },
  { symbol: "PRAJIND.NS", name: "PRAJ INDUSTRIES" },
  { symbol: "PREMIERENE.NS", name: "PREMIER ENERGIES" },
  { symbol: "PRESTIGE.NS", name: "PRESTIGE ESTATE" },
  { symbol: "PGHH.NS", name: "P&G HYGIENE & HEALTH CARE" },
  { symbol: "PNB.NS", name: "PUNJAB NATIONAL BANK" },
  { symbol: "RRKABEL.NS", name: "R R KABEL" },
  { symbol: "RBLBANK.NS", name: "RBL BANK" },
  { symbol: "RECLTD.NS", name: "REC" },
  { symbol: "RHIM.NS", name: "RHI MAGNESITA INDIA" },
  { symbol: "RITES.NS", name: "RITES" },
  { symbol: "RADICO.NS", name: "RADICO KHAITAN" },
  { symbol: "RVNL.NS", name: "RAIL VIKAS NIGAM" },
  { symbol: "RAILTEL.NS", name: "RAILTEL CORP OF IND" },
  { symbol: "RAINBOW.NS", name: "RAINBOW CHILDRENS MED" },
  { symbol: "RKFORGE.NS", name: "RAMKRISHNA FORGINGS" },
  { symbol: "RCF.NS", name: "RASHTRIYA CHEMICALS & FER" },
  { symbol: "REDINGTON.NS", name: "REDINGTON" },
  { symbol: "RELIANCE.NS", name: "RELIANCE INDUSTRIES" },
  { symbol: "RPOWER.NS", name: "RELIANCE POWER" },
  { symbol: "SBFC.NS", name: "SBFC FINANCE" },
  { symbol: "SBICARD.NS", name: "SBI CARDS & PAY SER" },
  { symbol: "SBILIFE.NS", name: "SBI LIFE INSURANCE CO" },
  { symbol: "SJVN.NS", name: "SJVN" },
  { symbol: "SRF.NS", name: "SRF" },
  { symbol: "SAGILITY.NS", name: "SAGILITY" },
  { symbol: "SAILIFE.NS", name: "SAI LIFE SCIENCES" },
  { symbol: "SAMMAANCAP.NS", name: "SAMMAAN CAPITAL" },
  { symbol: "MOTHERSON.NS", name: "SAMVRDHNA MTHRSN INTL" },
  { symbol: "SAPPHIRE.NS", name: "SAPPHIRE FOODS INDIA" },
  { symbol: "SARDAEN.NS", name: "SARDA ENERGY & MIN" },
  { symbol: "SAREGAMA.NS", name: "SAREGAMA INDIA" },
  { symbol: "SCHAEFFLER.NS", name: "SCHAEFFLER INDIA" },
  { symbol: "SCI.NS", name: "SHIPPING CORP OF INDIA LT" },
  { symbol: "SHREECEM.NS", name: "SHREE CEMENT" },
  { symbol: "SHRIRAMFIN.NS", name: "SHRIRAM FINANCE" },
  { symbol: "SHYAMMETL.NS", name: "SHYAM METALICS AND ENGY L" },
  { symbol: "ENRIN.NS", name: "SIEMENS ENERGY INDIA" },
  { symbol: "SIEMENS.NS", name: "SIEMENS" },
  { symbol: "SIGNATURE.NS", name: "SIGNATUREGLOBAL INDIA" },
  { symbol: "SOBHA.NS", name: "SOBHA" },
  { symbol: "SOLARINDS.NS", name: "SOLAR INDUSTRIES (I)" },
  { symbol: "SONACOMS.NS", name: "SONA BLW PRECISION FRGS L" },
  { symbol: "SONATSOFTW.NS", name: "SONATA SOFTWARE" },
  { symbol: "STARHEALTH.NS", name: "STAR HEALTH & AL INS CO L" },
  { symbol: "SBIN.NS", name: "STATE BANK OF INDIA" },
  { symbol: "SAIL.NS", name: "STEEL AUTHORITY OF INDIA" },
  { symbol: "SUMICHEM.NS", name: "SUMITOMO CHEM INDIA" },
  { symbol: "SUNPHARMA.NS", name: "SUN PHARMACEUTICAL IND L" },
  { symbol: "SUNTV.NS", name: "SUN TV NETWORK" },
  { symbol: "SUNDARMFIN.NS", name: "SUNDARAM FINANCE" },
  { symbol: "SUNDRMFAST.NS", name: "SUNDRAM FASTENERS" },
  { symbol: "SUPREMEIND.NS", name: "SUPREME INDUSTRIES" },
  { symbol: "SUZLON.NS", name: "SUZLON ENERGY" },
  { symbol: "SWANCORP.NS", name: "SWAN CORP" },
  { symbol: "SWIGGY.NS", name: "SWIGGY" },
  { symbol: "SYNGENE.NS", name: "SYNGENE INTERNATIONAL" },
  { symbol: "SYRMA.NS", name: "SYRMA SGS TECHNOLOGY" },
  { symbol: "TBOTEK.NS", name: "TBO TEK" },
  { symbol: "TVSMOTOR.NS", name: "TVS MOTOR COMPANY " },
  { symbol: "TATACHEM.NS", name: "TATA CHEMICALS" },
  { symbol: "TATACOMM.NS", name: "TATA COMMUNICATIONS" },
  { symbol: "TCS.NS", name: "TATA CONSULTANCY SERV LT" },
  { symbol: "TATACONSUM.NS", name: "TATA CONSUMER PRODUCT" },
  { symbol: "TATAELXSI.NS", name: "TATA ELXSI" },
  { symbol: "TATAINVEST.NS", name: "TATA INVESTMENT CORP" },
  { symbol: "TMPV.NS", name: "TATA MOTORS PASS VEH" },
  { symbol: "TATAPOWER.NS", name: "TATA POWER CO" },
  { symbol: "TATASTEEL.NS", name: "TATA STEEL" },
  { symbol: "TATATECH.NS", name: "TATA TECHNOLOGIES" },
  { symbol: "TTML.NS", name: "TATA TELESERV(MAHARASTRA)" },
  { symbol: "TECHM.NS", name: "TECH MAHINDRA" },
  { symbol: "TECHNOE.NS", name: "TECHNO ELEC & ENG CO." },
  { symbol: "TEJASNET.NS", name: "TEJAS NETWORKS" },
  { symbol: "NIACL.NS", name: "THE NEW INDIA ASSU CO" },
  { symbol: "RAMCOCEM.NS", name: "THE RAMCO CEMENTS" },
  { symbol: "THERMAX.NS", name: "THERMAX" },
  { symbol: "TIMKEN.NS", name: "TIMKEN INDIA" },
  { symbol: "TITAGARH.NS", name: "TITAGARH RAIL SYSTEMS" },
  { symbol: "TITAN.NS", name: "TITAN COMPANY" },
  { symbol: "TORNTPHARM.NS", name: "TORRENT PHARMACEUTICALS L" },
  { symbol: "TORNTPOWER.NS", name: "TORRENT POWER" },
  { symbol: "TARIL.NS", name: "TRANS & RECTI." },
  { symbol: "TRENT.NS", name: "TRENT" },
  { symbol: "TRIDENT.NS", name: "TRIDENT" },
  { symbol: "TRIVENI.NS", name: "TRIVENI ENGG. & INDS." },
  { symbol: "TRITURBINE.NS", name: "TRIVENI TURBINE" },
  { symbol: "TIINDIA.NS", name: "TUBE INVEST OF INDIA" },
  { symbol: "UCOBANK.NS", name: "UCO BANK" },
  { symbol: "UNOMINDA.NS", name: "UNO MINDA" },
  { symbol: "UPL.NS", name: "UPL" },
  { symbol: "UTIAMC.NS", name: "UTI ASSET MNGMT CO" },
  { symbol: "ULTRACEMCO.NS", name: "ULTRATECH CEMENT" },
  { symbol: "UNIONBANK.NS", name: "UNION BANK OF INDIA" },
  { symbol: "UBL.NS", name: "UNITED BREWERIES" },
  { symbol: "UNITDSPR.NS", name: "UNITED SPIRITS" },
  { symbol: "USHAMART.NS", name: "USHA MARTIN" },
  { symbol: "VGUARD.NS", name: "V-GUARD IND" },
  { symbol: "DBREALTY.NS", name: "VALOR ESTATE" },
  { symbol: "VTL.NS", name: "VARDHMAN TEXTILES" },
  { symbol: "VBL.NS", name: "VARUN BEVERAGES" },
  { symbol: "MANYAVAR.NS", name: "VEDANT FASHIONS" },
  { symbol: "VEDL.NS", name: "VEDANTA" },
  { symbol: "VENTIVE.NS", name: "VENTIVE HOSPITALITY" },
  { symbol: "VIJAYA.NS", name: "VIJAYA DIAGNOSTIC CEN" },
  { symbol: "VMM.NS", name: "VISHAL MEGA MART" },
  { symbol: "IDEA.NS", name: "VODAFONE IDEA" },
  { symbol: "VOLTAS.NS", name: "VOLTAS" },
  { symbol: "WAAREEENER.NS", name: "WAAREE ENERGIES" },
  { symbol: "WELCORP.NS", name: "WELSPUN CORP" },
  { symbol: "WELSPUNLIV.NS", name: "WELSPUN LIVING" },
  { symbol: "WHIRLPOOL.NS", name: "WHIRLPOOL OF INDIA" },
  { symbol: "WIPRO.NS", name: "WIPRO" },
  { symbol: "WOCKPHARMA.NS", name: "WOCKHARDT" },
  { symbol: "YESBANK.NS", name: "YES BANK" },
  { symbol: "ZFCVINDIA.NS", name: "ZF COM VE CTR SYS IND" },
  { symbol: "ZEEL.NS", name: "ZEE ENTERTAINMENT ENT" },
  { symbol: "ZENTEC.NS", name: "ZEN TECHNOLOGIES" },
  { symbol: "ZENSARTECH.NS", name: "ZENSAR TECHNOLOGIES " },
  { symbol: "ZYDUSLIFE.NS", name: "ZYDUS LIFESCIENCES" },
  { symbol: "ECLERX.NS", name: "ECLERX SERVICES" },
];
