// Curated list of NSE stocks with market cap > ₹1000 Cr (Nifty 500 + key mid-caps)
// Using .NS suffix for Yahoo Finance NSE data

export const NSE_UNIVERSE: { symbol: string; name: string }[] = [
  // Nifty 50 core
  { symbol: "RELIANCE.NS", name: "Reliance Industries" },
  { symbol: "TCS.NS", name: "TCS" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank" },
  { symbol: "INFY.NS", name: "Infosys" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel" },
  { symbol: "ITC.NS", name: "ITC" },
  { symbol: "SBIN.NS", name: "SBI" },
  { symbol: "LT.NS", name: "L&T" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
  { symbol: "AXISBANK.NS", name: "Axis Bank" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma" },
  { symbol: "TITAN.NS", name: "Titan Company" },
  { symbol: "WIPRO.NS", name: "Wipro" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement" },
  { symbol: "NESTLEIND.NS", name: "Nestle India" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors" },
  { symbol: "NTPC.NS", name: "NTPC" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corp" },
  { symbol: "TECHM.NS", name: "Tech Mahindra" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports" },
  { symbol: "COALINDIA.NS", name: "Coal India" },
  { symbol: "ONGC.NS", name: "ONGC" },
  { symbol: "DRREDDY.NS", name: "Dr Reddy's Labs" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv" },
  { symbol: "GRASIM.NS", name: "Grasim Industries" },
  { symbol: "CIPLA.NS", name: "Cipla" },
  { symbol: "DIVISLAB.NS", name: "Divi's Labs" },
  { symbol: "BPCL.NS", name: "BPCL" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp" },
  { symbol: "BRITANNIA.NS", name: "Britannia" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products" },
  { symbol: "HINDALCO.NS", name: "Hindalco" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto" },
  { symbol: "VEDL.NS", name: "Vedanta" },
  { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance" },

  // Nifty Next 50
  { symbol: "ADANIGREEN.NS", name: "Adani Green Energy" },
  { symbol: "ADANIPOWER.NS", name: "Adani Power" },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
  { symbol: "BEL.NS", name: "Bharat Electronics" },
  { symbol: "BOSCHLTD.NS", name: "Bosch" },
  { symbol: "CANBK.NS", name: "Canara Bank" },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Inv & Fin" },
  { symbol: "COLPAL.NS", name: "Colgate-Palmolive" },
  { symbol: "DABUR.NS", name: "Dabur India" },
  { symbol: "DLF.NS", name: "DLF" },
  { symbol: "GAIL.NS", name: "GAIL (India)" },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer" },
  { symbol: "HAVELLS.NS", name: "Havells India" },
  { symbol: "ICICIPRULI.NS", name: "ICICI Pru Life" },
  { symbol: "INDIGO.NS", name: "InterGlobe Aviation" },
  { symbol: "IOC.NS", name: "Indian Oil Corp" },
  { symbol: "IRCTC.NS", name: "IRCTC" },
  { symbol: "JINDALSTEL.NS", name: "Jindal Steel & Power" },
  { symbol: "LICI.NS", name: "Life Insurance Corp" },
  { symbol: "LTIM.NS", name: "LTIMindtree" },
  { symbol: "MARICO.NS", name: "Marico" },
  { symbol: "MCDOWELL-N.NS", name: "United Spirits" },
  { symbol: "MOTHERSON.NS", name: "Motherson Sumi" },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance" },
  { symbol: "NAUKRI.NS", name: "Info Edge (Naukri)" },
  { symbol: "PFC.NS", name: "Power Finance Corp" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries" },
  { symbol: "PNB.NS", name: "Punjab National Bank" },
  { symbol: "RECLTD.NS", name: "REC Ltd" },
  { symbol: "SAIL.NS", name: "SAIL" },
  { symbol: "SIEMENS.NS", name: "Siemens" },
  { symbol: "SRF.NS", name: "SRF" },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharma" },
  { symbol: "TRENT.NS", name: "Trent" },
  { symbol: "UNIONBANK.NS", name: "Union Bank of India" },
  { symbol: "ZOMATO.NS", name: "Zomato" },
  { symbol: "ZYDUSLIFE.NS", name: "Zydus Lifesciences" },

  // Nifty Midcap 150 (selected stocks > ₹1000 Cr)
  { symbol: "ABB.NS", name: "ABB India" },
  { symbol: "ABCAPITAL.NS", name: "Aditya Birla Capital" },
  { symbol: "ACC.NS", name: "ACC" },
  { symbol: "ALKEM.NS", name: "Alkem Labs" },
  { symbol: "ASHOKLEY.NS", name: "Ashok Leyland" },
  { symbol: "ASTRAL.NS", name: "Astral" },
  { symbol: "ATUL.NS", name: "Atul" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma" },
  { symbol: "BALKRISIND.NS", name: "Balkrishna Industries" },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank" },
  { symbol: "BATAINDIA.NS", name: "Bata India" },
  { symbol: "BERGEPAINT.NS", name: "Berger Paints" },
  { symbol: "BHEL.NS", name: "BHEL" },
  { symbol: "BIOCON.NS", name: "Biocon" },
  { symbol: "CANFINHOME.NS", name: "Can Fin Homes" },
  { symbol: "COFORGE.NS", name: "Coforge" },
  { symbol: "CONCOR.NS", name: "Container Corp" },
  { symbol: "CROMPTON.NS", name: "Crompton Greaves CE" },
  { symbol: "CUB.NS", name: "City Union Bank" },
  { symbol: "CUMMINSIND.NS", name: "Cummins India" },
  { symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite" },
  { symbol: "DELHIVERY.NS", name: "Delhivery" },
  { symbol: "DIXON.NS", name: "Dixon Technologies" },
  { symbol: "ESCORTS.NS", name: "Escorts Kubota" },
  { symbol: "EXIDEIND.NS", name: "Exide Industries" },
  { symbol: "FEDERALBNK.NS", name: "Federal Bank" },
  { symbol: "GLENMARK.NS", name: "Glenmark Pharma" },
  { symbol: "GMRINFRA.NS", name: "GMR Airports Infra" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties" },
  { symbol: "GRANULES.NS", name: "Granules India" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics" },
  { symbol: "HINDPETRO.NS", name: "HPCL" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank" },
  { symbol: "IEX.NS", name: "Indian Energy Exchange" },
  { symbol: "INDIANB.NS", name: "Indian Bank" },
  { symbol: "INDUSTOWER.NS", name: "Indus Towers" },
  { symbol: "IRFC.NS", name: "IRFC" },
  { symbol: "JUBLFOOD.NS", name: "Jubilant FoodWorks" },
  { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance" },
  { symbol: "LALPATHLAB.NS", name: "Dr Lal PathLabs" },
  { symbol: "LAURUSLABS.NS", name: "Laurus Labs" },
  { symbol: "LUPIN.NS", name: "Lupin" },
  { symbol: "MANAPPURAM.NS", name: "Manappuram Finance" },
  { symbol: "MAXHEALTH.NS", name: "Max Healthcare" },
  { symbol: "MCX.NS", name: "MCX" },
  { symbol: "MFSL.NS", name: "Max Financial Services" },
  { symbol: "MGL.NS", name: "Mahanagar Gas" },
  { symbol: "MPHASIS.NS", name: "Mphasis" },
  { symbol: "NAM-INDIA.NS", name: "Nippon Life India AMC" },
  { symbol: "NATIONALUM.NS", name: "NALCO" },
  { symbol: "NMDC.NS", name: "NMDC" },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty" },
  { symbol: "OFSS.NS", name: "Oracle Financial Services" },
  { symbol: "PAGEIND.NS", name: "Page Industries" },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems" },
  { symbol: "PETRONET.NS", name: "Petronet LNG" },
  { symbol: "PIIND.NS", name: "PI Industries" },
  { symbol: "POLYCAB.NS", name: "Polycab India" },
  { symbol: "PRESTIGE.NS", name: "Prestige Estates" },
  { symbol: "PVRINOX.NS", name: "PVR INOX" },
  { symbol: "RAMCOCEM.NS", name: "Ramco Cements" },
  { symbol: "RBLBANK.NS", name: "RBL Bank" },
  { symbol: "SOLARINDS.NS", name: "Solar Industries" },
  { symbol: "SONACOMS.NS", name: "Sona BLW Precision" },
  { symbol: "STARHEALTH.NS", name: "Star Health" },
  { symbol: "SUNTV.NS", name: "Sun TV Network" },
  { symbol: "SYNGENE.NS", name: "Syngene International" },
  { symbol: "TATACHEM.NS", name: "Tata Chemicals" },
  { symbol: "TATACOMM.NS", name: "Tata Communications" },
  { symbol: "TATAELXSI.NS", name: "Tata Elxsi" },
  { symbol: "TATAPOWER.NS", name: "Tata Power" },
  { symbol: "TIINDIA.NS", name: "Tube Investments" },
  { symbol: "TORNTPOWER.NS", name: "Torrent Power" },
  { symbol: "TVSMOTOR.NS", name: "TVS Motor" },
  { symbol: "UBL.NS", name: "United Breweries" },
  { symbol: "VOLTAS.NS", name: "Voltas" },
  { symbol: "WHIRLPOOL.NS", name: "Whirlpool India" },
  { symbol: "YESBANK.NS", name: "Yes Bank" },

  // Additional large & mid-cap stocks
  { symbol: "ABFRL.NS", name: "Aditya Birla Fashion" },
  { symbol: "AJANTPHARM.NS", name: "Ajanta Pharma" },
  { symbol: "APLLTD.NS", name: "Alembic Pharma" },
  { symbol: "AARTIIND.NS", name: "Aarti Industries" },
  { symbol: "AFFLE.NS", name: "Affle India" },
  { symbol: "ANGELONE.NS", name: "Angel One" },
  { symbol: "APLAPOLLO.NS", name: "APL Apollo Tubes" },
  { symbol: "RVNL.NS", name: "Rail Vikas Nigam" },
  { symbol: "SUZLON.NS", name: "Suzlon Energy" },
  { symbol: "NHPC.NS", name: "NHPC" },
  { symbol: "SJVN.NS", name: "SJVN" },
  { symbol: "HUDCO.NS", name: "HUDCO" },
  { symbol: "COCHINSHIP.NS", name: "Cochin Shipyard" },
  { symbol: "MAZAGON.NS", name: "Mazagon Dock Ship" },
  { symbol: "CESC.NS", name: "CESC" },
  { symbol: "SUPREMEIND.NS", name: "Supreme Industries" },
  { symbol: "CGPOWER.NS", name: "CG Power & Industrial" },
  { symbol: "KAYNES.NS", name: "Kaynes Technology" },
  { symbol: "PAYTM.NS", name: "One97 Communications" },
  { symbol: "NYKAA.NS", name: "FSN E-Commerce (Nykaa)" },
  { symbol: "POLICYBZR.NS", name: "PB Fintech" },
  { symbol: "DMART.NS", name: "Avenue Supermarts" },
  { symbol: "TATATECH.NS", name: "Tata Technologies" },
  { symbol: "JSWENERGY.NS", name: "JSW Energy" },
  { symbol: "KALYANKJIL.NS", name: "Kalyan Jewellers" },
  { symbol: "IDEA.NS", name: "Vodafone Idea" },
  { symbol: "ZEEL.NS", name: "Zee Entertainment" },
  { symbol: "PHOENIXLTD.NS", name: "Phoenix Mills" },
  { symbol: "LODHA.NS", name: "Macrotech Developers" },
  { symbol: "KEI.NS", name: "KEI Industries" },
];
